# Generated by Django 3.1.1 on 2020-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoicedetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
