# Generated by Django 3.1.1 on 2020-09-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20200906_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
